### ISSUE TITLE
When I test it, It's wrong

### ISSUE THREAD

**Issue by dulunar** [lambdalisue/txt2xls#2]
txt2xls -o output Sample*.txt
The Sample*.txt lines:
$ wl Sample*.txt
 6 Sample1.txt
 6 Sample2.txt
 6 Sample3.txt
18 total

But I get the error:
Validation Error
| The 'using' key in the section 'reader' failed validation. Please make
| sure the format of the value is correct.

Traceback (most recent call last):
  File "/usr/local/bin/txt2xls", line 10, in <module>
    sys.exit(txt2xls())
  File "/usr/local/lib/python2.7/dist-packages/txt2xls/console.py", line 21, in txt2xls
    collection = reader.read(args.infiles, fail_silently)
  File "/usr/local/lib/python2.7/dist-packages/txt2xls/reader/__init__.py", line 64, in read
    with_filename=True)
  File "/usr/local/lib/python2.7/dist-packages/maidenhair/functions.py", line 138, in load
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/maidenhair/loaders/base.py", line 139, in glob
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/maidenhair/loaders/base.py", line 72, in load
    return slice_columns(data, using)
  File "/usr/local/lib/python2.7/dist-packages/maidenhair/loaders/base.py", line 175, in slice_columns
    return [x[:,s] for s in using]
ValueError: invalid literal for long() with base 10: 'N'

Where is the wrong, Could you tell me? Thanks.

**Comment by lambdalisue** [comment]
It seems the value of `using` is wrong. Try `txt2xls -u 0:1:2:3:4:5 -o output Sample*.txt`
